/*
 * [y] hybris Platform
 *
 * Copyright (c) 2000-2015 hybris AG
 * All rights reserved.
 *
 * This software is the confidential and proprietary information of hybris
 * ("Confidential Information"). You shall not disclose such Confidential
 * Information and shall use it only in accordance with the terms of the
 * license agreement you entered into with hybris.
 *
 *
 */
package my.bookstore.facades.populators;

import de.hybris.platform.commercefacades.product.data.ProductData;
import de.hybris.platform.commerceservices.search.resultdata.SearchResultValueData;
import de.hybris.platform.converters.Populator;
import de.hybris.platform.servicelayer.dto.converter.ConversionException;

import java.util.Map;

import org.springframework.util.Assert;


public class SearchResultProductRewardPointsPopulator implements Populator<SearchResultValueData, ProductData>
{
	@Override
	public void populate(final SearchResultValueData source, final ProductData target) throws ConversionException
	{
		Assert.notNull(source, "Parameter source cannot be null.");
		Assert.notNull(target, "Parameter target cannot be null.");
		/*
		 * TODO exercise 10.1 Hint: This method's 'source' parameter is of type SearchResultValueData, a Java bean (POJO)
		 * generated by the Hybris build process. Here, this object represents a single "document" (think "row") from a
		 * Solr search result. The object has a method, getValues(), which returns a java.util.Map<String, Object>, where
		 * each entry is a name/value pair representing a single field. In this exercise, we are interested in the
		 * 'rewardPoints' field.
		 */

		final Map<String, Object> values = source.getValues();
		final Integer rewardPoints = (Integer) values.get("rewardPoints");

		target.setRewardPoints(rewardPoints == null ? Integer.valueOf(0) : rewardPoints);

	}
}